apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dotnetrepo
  description: |
    This is a test repository from Ash github account
  links:
    - title: Website
      url: https://github.com/ashthetis
    - title: Documentation
      url: https://backstage.io/docs/overview/what-is-backstage/
    - title: Storybook
      url: https://backstage.io/docs/overview/what-is-backstage/
    - title: Discord Chat
      url: https://backstage.io/docs/overview/what-is-backstage/
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: library
  owner: Ash Mcdoanlds
  lifecycle: experimental
